# Generated by Django 5.2 on 2025-04-28 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('has_completed_task', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='FingerPress',
        ),
        migrations.AddField(
            model_name='game',
            name='participants',
            field=models.ManyToManyField(related_name='games_participated', to='game.participant'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_won', to='game.participant'),
        ),
    ]
