# Generated by Django 5.2 on 2025-04-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_participant_delete_fingerpress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='is_active',
            new_name='elimination_mode',
        ),
        migrations.RemoveField(
            model_name='game',
            name='start_time',
        ),
        migrations.AddField(
            model_name='game',
            name='game_mode',
            field=models.CharField(choices=[('simple', 'Simple'), ('withTasks', 'With Tasks')], default='withTasks', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='task_difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='time_limit_seconds',
            field=models.IntegerField(default=5),
        ),
    ]
