# Generated by Django 5.2 on 2025-04-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_is_active_game_elimination_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='y',
            field=models.FloatField(default=0),
        ),
    ]
